In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

### 전처리
- ST-1035 / ST-454 / ST-471만 따로 빼서 저장하도록 한다.

In [2]:
df = pd.read_csv('../../Data/Zero/Temp/24년도_따릉이_이용건수.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)
# df1 = 
df1 = df[(df['전체_이용_분'] >= 5) & (df['전체_이용_거리'] >= 5)]
df1

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간
0,20241102,출발시간,ST-1584,잠실6동_004_1,ST-1603,능동_002_2,1.0,26.0,5070.0,935.0
1,20241102,출발시간,ST-2482,방화1동_023_1,ST-1254,방화1동_043_1,1.0,5.0,425.0,20.0
2,20241102,출발시간,ST-2020,등촌1동_025_1,X,NaN,1.0,18.0,1694.0,1455.0
3,20241102,출발시간,ST-358,왕십리도선동_049_1,ST-2508,용신동_060_1,2.0,14.0,1175.0,2020.0
4,20241102,출발시간,ST-3149,중계4동_002_1,ST-3116,"상계6,7동_005_1",1.0,10.0,3290.0,820.0
...,...,...,...,...,...,...,...,...,...,...
81615643,20240205,도착시간,ST-513,가양1동_049_1,ST-824,방화1동_038_1,1.0,5.0,859.0,2355.0
81615644,20240205,도착시간,ST-678,개봉1동_046_1,ST-1523,고척2동_023_1,1.0,6.0,1383.0,2355.0
81615645,20240205,도착시간,ST-737,가락본동_025_1,ST-737,가락본동_025_1,1.0,8.0,308.0,2355.0
81615646,20240205,도착시간,ST-788,논현1동_004_1,ST-1900,서초4동_048_1,1.0,43.0,2200.0,2355.0
81615648,20240205,도착시간,ST-9,서교동_010_2,ST-341,연남동_016_1,1.0,6.0,982.0,2355.0

In [13]:
col = ['ST-1035','ST-454','ST-471']

# df_section6 = df1[(df1['시작_대여소_ID'].isin(col) & df1['집계_기준']=='출발시간') | (df1['종료_대여소_ID'].isin(col) & df1['집계_기준']=='도착시간')]
cond1 = (df1['시작_대여소_ID'].isin(col)) & (df1['집계_기준'] == '출발시간')
cond2 = (df1['종료_대여소_ID'].isin(col)) & (df1['집계_기준'] == '도착시간')

df_section6 = df1[cond1 | cond2]
df_section6['시'] = df_section6['기준_시간'] / 100
df_section6['분'] = df_section6['기준_시간'] % 100
df_section6['시'] = df_section6['시'].astype(int)
df_section6['분'] = df_section6['분'].astype(int)
df_section6.sort_values(['기준_날짜','시','분'],ascending=True,inplace=True)
df_section6.reset_index(drop=True, inplace=True)
df_section6

,기준_날짜,집계_기준,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,기준_시간,시,분
0,20240101,출발시간,ST-454,대조동_024_1,ST-1331,응암3동_002_1,1.0,115.0,11170.0,5.0,0,5
1,20240101,출발시간,ST-454,대조동_024_1,ST-1036,역촌동_001_1,1.0,5.0,860.0,15.0,0,15
2,20240101,출발시간,ST-1035,불광2동_021_1,ST-3058,진관동_038_8,1.0,14.0,1821.0,20.0,0,20
3,20240101,출발시간,ST-454,대조동_024_1,ST-349,북가좌1동_008_1,1.0,26.0,4473.0,20.0,0,20
4,20240101,출발시간,ST-454,대조동_024_1,ST-1025,응암1동_005_1,1.0,12.0,1960.0,25.0,0,25
...,...,...,...,...,...,...,...,...,...,...,...,...
86154,20241231,출발시간,ST-454,대조동_020_1,ST-1036,역촌동_044_1,1.0,5.0,860.0,2335.0,23,35
86155,20241231,출발시간,ST-454,대조동_020_1,ST-455,응암1동_023_1,2.0,38.0,4182.0,2335.0,23,35
86156,20241231,출발시간,ST-454,대조동_020_1,ST-459,녹번동_043_1,1.0,10.0,1490.0,2340.0,23,40
86157,20241231,도착시간,ST-3169,구산동_060_1,ST-454,대조동_020_1,1.0,8.0,3030.0,2340.0,23,40
86158,20241231,도착시간,ST-2979,연남동_029_2,ST-454,대조동_020_1,1.0,48.0,8747.0,2355.0,23,55

In [ ]:
# df_section6.to_csv('../../Data/Zero/section6.csv',index=None)

In [3]:
import pandas as pd
from glob import glob
station_files = glob('../../Data/Zero/2025/*.csv')
station_files = sorted(station_files)
station_files

['../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250101.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250102.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250103.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250104.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250105.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250106.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250107.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250108.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250109.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250110.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250111.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250112.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250113.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250114.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250115.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250116.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250117.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250118.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250119.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250120.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250121.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250122.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250123.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250124.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250125.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250126.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250127.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250128.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250129.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250130.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250131.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250201.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250202.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250203.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250204.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250205.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250206.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250207.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250208.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250209.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250210.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250211.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250212.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250213.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250214.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250215.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250216.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250217.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250218.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250219.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250220.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250221.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250222.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250223.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250224.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250225.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250226.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250227.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250228.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250301.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250302.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250303.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250304.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250305.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250306.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250307.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250308.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250309.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250310.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250311.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250312.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250313.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250314.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250315.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250316.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250317.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250318.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250319.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250320.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250321.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250322.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250323.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250324.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250325.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250326.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250327.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250328.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250329.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250330.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250331.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250401.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250402.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250403.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250404.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250405.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250406.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250407.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250408.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250409.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250410.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250411.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250412.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250413.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250414.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250415.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250416.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250417.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250418.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250419.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250420.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250421.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250422.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250423.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250424.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250425.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250426.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250427.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250428.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250429.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250430.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250501.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250502.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250503.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250504.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250505.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250506.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250507.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250508.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250509.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250510.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250511.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250512.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250513.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250514.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250515.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250516.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250517.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250518.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250519.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250520.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250521.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250522.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250523.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250524.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250525.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250526.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250527.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250528.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250529.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250530.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250531.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250601.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250602.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250603.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250604.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250605.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250606.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250607.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250608.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250609.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250610.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250611.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250612.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250613.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250614.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250615.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250616.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250617.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250618.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250619.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250620.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250621.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250622.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250623.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250624.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250625.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250626.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250627.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250628.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250629.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250630.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250701.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250702.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250703.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250704.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250705.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250706.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250707.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250708.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250709.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250710.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250711.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250712.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250713.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250714.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250715.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250716.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250717.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250718.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250719.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250720.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250721.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250722.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250723.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250724.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250725.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250726.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250727.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250728.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250729.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250730.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250731.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250801.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250802.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250803.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250804.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250805.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250806.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250807.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250808.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250809.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250810.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250811.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250812.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250813.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250814.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250815.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250816.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250817.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250818.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250819.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250820.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250821.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250822.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250823.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250824.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250825.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250826.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250827.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250828.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250829.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250830.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250831.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250901.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250902.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250903.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250904.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250905.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250906.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250907.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250908.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250909.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250910.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250911.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250912.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250913.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250914.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250915.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250916.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250917.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250918.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250919.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250920.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250921.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250922.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250923.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250924.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250925.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250926.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250927.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250928.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250929.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250930.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251001.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251002.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251003.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251004.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251005.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251006.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251007.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251008.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251009.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251010.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251011.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251012.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251013.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251014.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251015.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251016.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251017.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251018.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251019.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251020.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251021.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251022.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251023.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251024.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251025.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251026.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251027.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251028.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251029.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251030.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251031.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251101.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251102.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251103.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251104.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251105.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251106.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251107.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251108.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251109.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251110.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251111.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251112.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251113.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251114.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251115.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251116.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251117.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251118.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251119.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251120.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251121.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251122.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251123.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251124.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251125.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251126.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251127.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251128.csv',
 '../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251129.csv',

In [19]:
tmp_raw = []

for file_name in station_files:
    print(file_name)
    try:
        tmp = pd.read_csv(file_name, encoding='euc-kr', encoding_errors='ignore')
    except:
        tmp = pd.read_csv(file_name, encoding='cp949', encoding_errors='ignore')
    tmp_raw.append(tmp)

station_raw = pd.concat(tmp_raw,axis=0)

../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250101.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250102.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250103.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250104.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250105.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250106.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250107.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250108.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250109.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250110.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250111.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250112.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250113.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250114.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250115.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250116.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250117.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250118.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250119.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250120.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250121.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250122.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250123.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250124.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250125.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250126.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250127.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250128.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250129.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250130.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250131.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250201.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250202.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250203.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250204.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250205.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250206.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250207.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250208.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250209.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250210.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250211.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250212.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250213.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250214.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250215.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250216.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250217.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250218.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250219.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250220.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250221.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250222.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250223.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250224.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250225.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250226.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250227.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250228.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250301.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250302.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250303.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250304.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250305.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250306.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250307.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250308.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250309.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250310.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250311.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250312.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250313.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250314.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250315.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250316.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250317.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250318.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250319.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250320.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250321.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250322.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250323.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250324.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250325.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250326.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250327.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250328.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250329.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250330.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250331.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250401.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250402.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250403.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250404.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250405.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250406.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250407.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250408.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250409.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250410.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250411.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250412.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250413.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250414.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250415.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250416.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250417.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250418.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250419.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250420.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250421.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250422.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250423.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250424.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250425.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250426.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250427.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250428.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250429.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250430.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250501.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250502.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250503.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250504.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250505.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250506.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250507.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250508.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250509.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250510.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250511.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250512.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250513.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250514.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250515.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250516.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250517.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250518.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250519.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250520.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250521.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250522.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250523.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250524.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250525.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250526.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250527.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250528.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250529.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250530.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250531.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250601.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250602.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250603.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250604.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250605.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250606.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250607.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250608.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250609.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250610.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250611.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250612.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250613.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250614.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250615.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250616.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250617.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250618.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250619.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250620.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250621.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250622.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250623.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250624.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250625.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250626.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250627.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250628.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250629.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250630.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250701.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250702.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250703.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250704.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250705.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250706.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250707.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250708.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250709.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250710.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250711.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250712.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250713.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250714.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250715.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250716.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250717.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250718.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250719.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250720.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250721.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250722.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250723.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250724.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250725.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250726.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250727.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250728.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250729.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250730.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250731.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250801.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250802.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250803.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250804.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250805.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250806.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250807.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250808.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250809.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250810.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250811.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250812.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250813.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250814.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250815.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250816.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250817.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250818.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250819.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250820.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250821.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250822.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250823.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250824.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250825.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250826.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250827.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250828.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250829.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250830.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250831.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250901.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250902.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250903.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250904.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250905.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250906.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250907.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250908.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250909.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250910.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250911.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250912.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250913.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250914.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250915.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250916.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250917.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250918.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250919.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250920.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250921.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250922.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250923.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250924.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250925.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250926.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250927.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250928.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250929.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20250930.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251001.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251002.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251003.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251004.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251005.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251006.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251007.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251008.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251009.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251010.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251011.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251012.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251013.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251014.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251015.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251016.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251017.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251018.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251019.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251020.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251021.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251022.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251023.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251024.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251025.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251026.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251027.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251028.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251029.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251030.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251031.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251101.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251102.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251103.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251104.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251105.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251106.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251107.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251108.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251109.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251110.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251111.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251112.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251113.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251114.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251115.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251116.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251117.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251118.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251119.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251120.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251121.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251122.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251123.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251124.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251125.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251126.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251127.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251128.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251129.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251130.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251201.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251202.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251203.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251204.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251205.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251206.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251207.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251208.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251209.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251210.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251211.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251212.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251213.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251214.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251215.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251216.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251217.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251218.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251219.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251220.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251221.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251222.csv
../../Data/Zero/2025/tpss_bcycl_od_statnhm_20251223.csv

In [36]:
station_raw1 = station_raw.iloc[:,9+1:]

In [23]:
station_raw1.info()

<class 'pandas.DataFrame'>
Index: 68023993 entries, 0 to 106565
Data columns (total 10 columns):
 #   Column     Dtype
---  ------     -----
 0   기준_날짜      float64
 1   집계_기준      str
 2   기준_시간대     float64
 3   시작_대여소_ID  str
 4   시작_대여소명    str
 5   종료_대여소_ID  str
 6   종료_대여소명    str
 7   전체_건수      float64
 8   전체_이용_분    float64
 9   전체_이용_거리   float64
dtypes: float64(5), str(5)
memory usage: 9.2 GB

In [53]:
station_raw1['기준_날짜'] = station_raw1['기준_날짜'].astype(int)
station_raw1['전체_건수'] = station_raw1['전체_건수'].astype(int)
station_raw1['전체_이용_분'] = station_raw1['전체_이용_분'].fillna(0)
station_raw1['전체_이용_분'] = station_raw1['전체_이용_분'].astype(int)
station_raw1['전체_이용_거리'] = station_raw1['전체_이용_거리'].fillna(0)
station_raw1['전체_이용_거리'] = station_raw1['전체_이용_거리'].astype(int)

In [54]:
station_raw1.to_csv('../../Data/2025_data.csv')

In [25]:
import pyarrow as pa
import pyarrow.parquet as pq

In [62]:
csv_file = "../../Data/2025.csv"
parquet_file = "../../Data/2025_data.parquet"
chunksize = 500
csv_stream = pd.read_csv(csv_file, sep=',', chunksize=chunksize, low_memory=False)
chunk =next(iter(csv_stream))

In [63]:
parquet_schema_old = pa.Table.from_pandas(df=chunk).schema
parquet_schema_new = pa.schema([
    ('기준_날짜', pa.int64()),
    ('집계_기준', pa.string()),
    ('기준_시간대', pa.float64()),
    ('시작_대여소_ID', pa.string()),
    ('시작_대여소명', pa.string()),
    ('종료_대여소_ID', pa.string()),
    ('종료_대여소명', pa.string()),
    ('전체_건수', pa.float64()),
    ('전체_이용_분', pa.float64()),
    ('전체_이용_거리', pa.float64()),
    
])
parquet_schema_old == parquet_schema_new

False

In [48]:
chunksize = 500
csv_stream = pd.read_csv(csv_file, sep=',', chunksize=chunksize, low_memory=False)
for i, chunk in enumerate(csv_stream):
    print("Chunk", i)
    if i == 0:
        # Guess the schema of the CSV file from the first chunk
        parquet_schema = parquet_schema_new
        # Open a Parquet file for writing
        parquet_writer = pq.ParquetWriter(parquet_file, parquet_schema, compression='snappy')
    # Write CSV chunk to the parquet file
    table = pa.Table.from_pandas(chunk, schema=parquet_schema)
    parquet_writer.write_table(table)
else :
    parquet_writer.close()

Chunk 0
Chunk 1
Chunk 2
Chunk 3
Chunk 4
Chunk 5
Chunk 6
Chunk 7
Chunk 8
Chunk 9
Chunk 10
Chunk 11
Chunk 12
Chunk 13
Chunk 14
Chunk 15
Chunk 16
Chunk 17
Chunk 18
Chunk 19
Chunk 20
Chunk 21
Chunk 22
Chunk 23
Chunk 24
Chunk 25
Chunk 26
Chunk 27
Chunk 28
Chunk 29
Chunk 30
Chunk 31
Chunk 32
Chunk 33
Chunk 34
Chunk 35
Chunk 36
Chunk 37
Chunk 38
Chunk 39
Chunk 40
Chunk 41
Chunk 42
Chunk 43
Chunk 44
Chunk 45
Chunk 46
Chunk 47
Chunk 48
Chunk 49
Chunk 50
Chunk 51
Chunk 52
Chunk 53
Chunk 54
Chunk 55
Chunk 56
Chunk 57
Chunk 58
Chunk 59
Chunk 60
Chunk 61
Chunk 62
Chunk 63
Chunk 64
Chunk 65
Chunk 66
Chunk 67
Chunk 68
Chunk 69
Chunk 70
Chunk 71
Chunk 72
Chunk 73
Chunk 74
Chunk 75
Chunk 76
Chunk 77
Chunk 78
Chunk 79
Chunk 80
Chunk 81
Chunk 82
Chunk 83
Chunk 84
Chunk 85
Chunk 86
Chunk 87
Chunk 88
Chunk 89
Chunk 90
Chunk 91
Chunk 92
Chunk 93
Chunk 94
Chunk 95
Chunk 96
Chunk 97
Chunk 98
Chunk 99
Chunk 100
Chunk 101
Chunk 102
Chunk 103
Chunk 104
Chunk 105
Chunk 106
Chunk 107
Chunk 108
Chunk 109
Chunk 110
Chunk 111
Chunk 112
Chunk 113
Chunk 114
Chunk 115
Chunk 116
Chunk 117
Chunk 118
Chunk 119
Chunk 120
Chunk 121
Chunk 122
Chunk 123
Chunk 124
Chunk 125
Chunk 126
Chunk 127
Chunk 128
Chunk 129
Chunk 130
Chunk 131
Chunk 132
Chunk 133
Chunk 134
Chunk 135
Chunk 136
Chunk 137
Chunk 138
Chunk 139
Chunk 140
Chunk 141
Chunk 142
Chunk 143
Chunk 144
Chunk 145
Chunk 146
Chunk 147
Chunk 148
Chunk 149
Chunk 150
Chunk 151
Chunk 152
Chunk 153
Chunk 154
Chunk 155
Chunk 156
Chunk 157
Chunk 158
Chunk 159
Chunk 160
Chunk 161
Chunk 162
Chunk 163
Chunk 164
Chunk 165
Chunk 166
Chunk 167
Chunk 168
Chunk 169
Chunk 170
Chunk 171
Chunk 172
Chunk 173
Chunk 174
Chunk 175
Chunk 176
Chunk 177
Chunk 178
Chunk 179
Chunk 180
Chunk 181
Chunk 182
Chunk 183
Chunk 184
Chunk 185
Chunk 186
Chunk 187
Chunk 188
Chunk 189
Chunk 190
Chunk 191
Chunk 192
Chunk 193
Chunk 194
Chunk 195
Chunk 196
Chunk 197
Chunk 198
Chunk 199
Chunk 200
Chunk 201
Chunk 202
Chunk 203
Chunk 204
Chunk 205
Chunk 206
Chunk 207
Chunk 208
Chunk 209
Chunk 210
Chunk 211
Chunk 212
Chunk 213
Chunk 214
Chunk 215
Chunk 216
Chunk 217
Chunk 218
Chunk 219
Chunk 220
Chunk 221
Chunk 222
Chunk 223
Chunk 224
Chunk 225
Chunk 226
Chunk 227
Chunk 228
Chunk 229
Chunk 230
Chunk 231
Chunk 232
Chunk 233
Chunk 234
Chunk 235
Chunk 236
Chunk 237
Chunk 238
Chunk 239
Chunk 240
Chunk 241
Chunk 242
Chunk 243
Chunk 244
Chunk 245
Chunk 246
Chunk 247
Chunk 248
Chunk 249
Chunk 250
Chunk 251
Chunk 252
Chunk 253
Chunk 254
Chunk 255
Chunk 256
Chunk 257
Chunk 258
Chunk 259
Chunk 260
Chunk 261
Chunk 262
Chunk 263
Chunk 264
Chunk 265
Chunk 266
Chunk 267
Chunk 268
Chunk 269
Chunk 270
Chunk 271
Chunk 272
Chunk 273
Chunk 274
Chunk 275
Chunk 276
Chunk 277
Chunk 278
Chunk 279
Chunk 280
Chunk 281
Chunk 282
Chunk 283
Chunk 284
Chunk 285
Chunk 286
Chunk 287
Chunk 288
Chunk 289
Chunk 290
Chunk 291
Chunk 292
Chunk 293
Chunk 294
Chunk 295
Chunk 296
Chunk 297
Chunk 298
Chunk 299
Chunk 300
Chunk 301
Chunk 302
Chunk 303
Chunk 304
Chunk 305
Chunk 306
Chunk 307
Chunk 308
Chunk 309
Chunk 310
Chunk 311
Chunk 312
Chunk 313
Chunk 314
Chunk 315
Chunk 316
Chunk 317
Chunk 318
Chunk 319
Chunk 320
Chunk 321
Chunk 322
Chunk 323
Chunk 324
Chunk 325
Chunk 326
Chunk 327
Chunk 328
Chunk 329
Chunk 330
Chunk 331
Chunk 332
Chunk 333
Chunk 334
Chunk 335
Chunk 336
Chunk 337
Chunk 338
Chunk 339
Chunk 340
Chunk 341
Chunk 342
Chunk 343
Chunk 344
Chunk 345
Chunk 346
Chunk 347
Chunk 348
Chunk 349
Chunk 350
Chunk 351
Chunk 352
Chunk 353
Chunk 354
Chunk 355
Chunk 356
Chunk 357
Chunk 358
Chunk 359
Chunk 360
Chunk 361
Chunk 362
Chunk 363
Chunk 364
Chunk 365
Chunk 366
Chunk 367
Chunk 368
Chunk 369
Chunk 370
Chunk 371
Chunk 372
Chunk 373
Chunk 374
Chunk 375
Chunk 376
Chunk 377
Chunk 378
Chunk 379
Chunk 380
Chunk 381
Chunk 382
Chunk 383
Chunk 384
Chunk 385
Chunk 386
Chunk 387
Chunk 388
Chunk 389
Chunk 390
Chunk 391
Chunk 392
Chunk 393
Chunk 394
Chunk 395
Chunk 396
Chunk 397
Chunk 398
Chunk 399
Chunk 400
Chunk 401
Chunk 402
Chunk 403
Chunk 404
Chunk 405
Chunk 406
Chunk 407
Chunk 408
Chunk 409
Chunk 410
Chunk 411
Chunk 412
Chunk 413
Chunk 414
Chunk 415
Chunk 416
Chunk 417
Chunk 418
Chunk 419
Chunk 420
Chunk 421
Chunk 422
Chunk 423
Chunk 424
Chunk 425
Chunk 426
Chunk 427
Chunk 428
Chunk 429
Chunk 430
Chunk 431
Chunk 432
Chunk 433
Chunk 434
Chunk 435
Chunk 436
Chunk 437
Chunk 438
Chunk 439
Chunk 440
Chunk 441
Chunk 442
Chunk 443
Chunk 444
Chunk 445
Chunk 446
Chunk 447
Chunk 448
Chunk 449
Chunk 450
Chunk 451
Chunk 452
Chunk 453
Chunk 454
Chunk 455
Chunk 456
Chunk 457
Chunk 458
Chunk 459
Chunk 460
Chunk 461
Chunk 462
Chunk 463
Chunk 464
Chunk 465
Chunk 466
Chunk 467
Chunk 468
Chunk 469
Chunk 470
Chunk 471
Chunk 472
Chunk 473
Chunk 474
Chunk 475
Chunk 476
Chunk 477
Chunk 478
Chunk 479
Chunk 480
Chunk 481
Chunk 482
Chunk 483
Chunk 484
Chunk 485
Chunk 486
Chunk 487
Chunk 488
Chunk 489
Chunk 490
Chunk 491
Chunk 492
Chunk 493
Chunk 494
Chunk 495
Chunk 496
Chunk 497
Chunk 498
Chunk 499
Chunk 500
Chunk 501
Chunk 502
Chunk 503
Chunk 504
Chunk 505
Chunk 506
Chunk 507
Chunk 508
Chunk 509
Chunk 510
Chunk 511
Chunk 512
Chunk 513
Chunk 514
Chunk 515
Chunk 516
Chunk 517
Chunk 518
Chunk 519
Chunk 520
Chunk 521
Chunk 522
Chunk 523
Chunk 524
Chunk 525
Chunk 526
Chunk 527
Chunk 528
Chunk 529
Chunk 530
Chunk 531
Chunk 532
Chunk 533
Chunk 534
Chunk 535
Chunk 536
Chunk 537
Chunk 538
Chunk 539
Chunk 540
Chunk 541
Chunk 542
Chunk 543
Chunk 544
Chunk 545
Chunk 546
Chunk 547
Chunk 548
Chunk 549
Chunk 550
Chunk 551
Chunk 552
Chunk 553
Chunk 554
Chunk 555
Chunk 556
Chunk 557
Chunk 558
Chunk 559
Chunk 560
Chunk 561
Chunk 562
Chunk 563
Chunk 564
Chunk 565
Chunk 566
Chunk 567
Chunk 568
Chunk 569
Chunk 570
Chunk 571
Chunk 572
Chunk 573
Chunk 574
Chunk 575
Chunk 576
Chunk 577
Chunk 578
Chunk 579
Chunk 580
Chunk 581
Chunk 582
Chunk 583
Chunk 584
Chunk 585
Chunk 586
Chunk 587
Chunk 588
Chunk 589
Chunk 590
Chunk 591
Chunk 592
Chunk 593
Chunk 594
Chunk 595
Chunk 596
Chunk 597
Chunk 598
Chunk 599
Chunk 600
Chunk 601
Chunk 602
Chunk 603
Chunk 604
Chunk 605
Chunk 606
Chunk 607
Chunk 608
Chunk 609
Chunk 610
Chunk 611
Chunk 612
Chunk 613
Chunk 614
Chunk 615
Chunk 616
Chunk 617
Chunk 618
Chunk 619
Chunk 620
Chunk 621
Chunk 622
Chunk 623
Chunk 624
Chunk 625
Chunk 626
Chunk 627
Chunk 628
Chunk 629
Chunk 630
Chunk 631
Chunk 632
Chunk 633
Chunk 634
Chunk 635
Chunk 636
Chunk 637
Chunk 638
Chunk 639
Chunk 640
Chunk 641
Chunk 642
Chunk 643
Chunk 644
Chunk 645
Chunk 646
Chunk 647
Chunk 648
Chunk 649
Chunk 650
Chunk 651
Chunk 652
Chunk 653
Chunk 654
Chunk 655
Chunk 656
Chunk 657
Chunk 658
Chunk 659
Chunk 660
Chunk 661
Chunk 662
Chunk 663
Chunk 664
Chunk 665
Chunk 666
Chunk 667
Chunk 668
Chunk 669
Chunk 670
Chunk 671
Chunk 672
Chunk 673
Chunk 674
Chunk 675
Chunk 676
Chunk 677
Chunk 678
Chunk 679
Chunk 680
Chunk 681
Chunk 682
Chunk 683
Chunk 684
Chunk 685
Chunk 686
Chunk 687
Chunk 688
Chunk 689
Chunk 690
Chunk 691
Chunk 692
Chunk 693
Chunk 694
Chunk 695
Chunk 696
Chunk 697
Chunk 698
Chunk 699
Chunk 700
Chunk 701
Chunk 702
Chunk 703
Chunk 704
Chunk 705
Chunk 706
Chunk 707
Chunk 708
Chunk 709
Chunk 710
Chunk 711
Chunk 712
Chunk 713
Chunk 714
Chunk 715
Chunk 716
Chunk 717
Chunk 718
Chunk 719
Chunk 720
Chunk 721
Chunk 722
Chunk 723
Chunk 724
Chunk 725
Chunk 726
Chunk 727
Chunk 728
Chunk 729
Chunk 730
Chunk 731
Chunk 732
Chunk 733
Chunk 734
Chunk 735
Chunk 736
Chunk 737
Chunk 738
Chunk 739
Chunk 740
Chunk 741
Chunk 742
Chunk 743
Chunk 744
Chunk 745
Chunk 746
Chunk 747
Chunk 748
Chunk 749
Chunk 750
Chunk 751
Chunk 752
Chunk 753
Chunk 754
Chunk 755
Chunk 756
Chunk 757
Chunk 758
Chunk 759
Chunk 760
Chunk 761
Chunk 762
Chunk 763
Chunk 764
Chunk 765
Chunk 766
Chunk 767
Chunk 768
Chunk 769
Chunk 770
Chunk 771
Chunk 772
Chunk 773
Chunk 774
Chunk 775
Chunk 776
Chunk 777
Chunk 778
Chunk 779
Chunk 780
Chunk 781
Chunk 782
Chunk 783
Chunk 784
Chunk 785
Chunk 786
Chunk 787
Chunk 788
Chunk 789
Chunk 790
Chunk 791
Chunk 792
Chunk 793
Chunk 794
Chunk 795
Chunk 796
Chunk 797
Chunk 798
Chunk 799
Chunk 800
Chunk 801
Chunk 802
Chunk 803
Chunk 804
Chunk 805
Chunk 806
Chunk 807
Chunk 808
Chunk 809
Chunk 810
Chunk 811
Chunk 812
Chunk 813
Chunk 814
Chunk 815
Chunk 816
Chunk 817
Chunk 818
Chunk 819
Chunk 820
Chunk 821
Chunk 822
Chunk 823
Chunk 824
Chunk 825
Chunk 826
Chunk 827
Chunk 828
Chunk 829
Chunk 830
Chunk 831
Chunk 832
Chunk 833
Chunk 834
Chunk 835
Chunk 836
Chunk 837
Chunk 838
Chunk 839
Chunk 840
Chunk 841
Chunk 842
Chunk 843
Chunk 844
Chunk 845
Chunk 846
Chunk 847
Chunk 848
Chunk 849
Chunk 850
Chunk 851
Chunk 852
Chunk 853
Chunk 854
Chunk 855
Chunk 856
Chunk 857
Chunk 858
Chunk 859
Chunk 860
Chunk 861
Chunk 862
Chunk 863
Chunk 864
Chunk 865
Chunk 866
Chunk 867
Chunk 868
Chunk 869
Chunk 870
Chunk 871
Chunk 872
Chunk 873
Chunk 874
Chunk 875
Chunk 876
Chunk 877
Chunk 878
Chunk 879
Chunk 880
Chunk 881
Chunk 882
Chunk 883
Chunk 884
Chunk 885
Chunk 886
Chunk 887
Chunk 888
Chunk 889
Chunk 890
Chunk 891
Chunk 892
Chunk 893
Chunk 894
Chunk 895
Chunk 896
Chunk 897
Chunk 898
Chunk 899
Chunk 900
Chunk 901
Chunk 902
Chunk 903
Chunk 904
Chunk 905
Chunk 906
Chunk 907
Chunk 908
Chunk 909
Chunk 910
Chunk 911
Chunk 912
Chunk 913
Chunk 914
Chunk 915
Chunk 916
Chunk 917
Chunk 918
Chunk 919
Chunk 920
Chunk 921
Chunk 922
Chunk 923
Chunk 924
Chunk 925
Chunk 926
Chunk 927
Chunk 928
Chunk 929
Chunk 930
Chunk 931
Chunk 932
Chunk 933
Chunk 934
Chunk 935
Chunk 936
Chunk 937
Chunk 938
Chunk 939
Chunk 940
Chunk 941
Chunk 942
Chunk 943
Chunk 944
Chunk 945
Chunk 946
Chunk 947
Chunk 948
Chunk 949
Chunk 950
Chunk 951
Chunk 952
Chunk 953
Chunk 954
Chunk 955
Chunk 956
Chunk 957
Chunk 958
Chunk 959
Chunk 960
Chunk 961
Chunk 962
Chunk 963
Chunk 964
Chunk 965
Chunk 966
Chunk 967
Chunk 968
Chunk 969
Chunk 970
Chunk 971
Chunk 972
Chunk 973
Chunk 974
Chunk 975
Chunk 976
Chunk 977
Chunk 978
Chunk 979
Chunk 980
Chunk 981
Chunk 982
Chunk 983
Chunk 984
Chunk 985
Chunk 986
Chunk 987
Chunk 988
Chunk 989
Chunk 990
Chunk 991
Chunk 992
Chunk 993
Chunk 994
Chunk 995
Chunk 996
Chunk 997
Chunk 998
Chunk 999
Chunk 1000
Chunk 1001
Chunk 1002
Chunk 1003
Chunk 1004
Chunk 1005
Chunk 1006
Chunk 1007
Chunk 1008
Chunk 1009
Chunk 1010
Chunk 1011
Chunk 1012
Chunk 1013
Chunk 1014
Chunk 1015
Chunk 1016
Chunk 1017
Chunk 1018
Chunk 1019
Chunk 1020
Chunk 1021
Chunk 1022
Chunk 1023
Chunk 1024
Chunk 1025
Chunk 1026
Chunk 1027
Chunk 1028
Chunk 1029
Chunk 1030
Chunk 1031
Chunk 1032
Chunk 1033
Chunk 1034
Chunk 1035
Chunk 1036
Chunk 1037
Chunk 1038
Chunk 1039
Chunk 1040
Chunk 1041
Chunk 1042
Chunk 1043
Chunk 1044
Chunk 1045
Chunk 1046
Chunk 1047
Chunk 1048
Chunk 1049
Chunk 1050
Chunk 1051
Chunk 1052
Chunk 1053
Chunk 1054
Chunk 1055
Chunk 1056
Chunk 1057
Chunk 1058
Chunk 1059
Chunk 1060
Chunk 1061
Chunk 1062
Chunk 1063
Chunk 1064
Chunk 1065
Chunk 1066
Chunk 1067
Chunk 1068
Chunk 1069
Chunk 1070
Chunk 1071
Chunk 1072
Chunk 1073
Chunk 1074
Chunk 1075
Chunk 1076
Chunk 1077
Chunk 1078
Chunk 1079
Chunk 1080
Chunk 1081
Chunk 1082
Chunk 1083
Chunk 1084
Chunk 1085
Chunk 1086
Chunk 1087
Chunk 1088
Chunk 1089
Chunk 1090
Chunk 1091
Chunk 1092
Chunk 1093
Chunk 1094
Chunk 1095
Chunk 1096
Chunk 1097
Chunk 1098
Chunk 1099
Chunk 1100
Chunk 1101
Chunk 1102
Chunk 1103
Chunk 1104
Chunk 1105
Chunk 1106
Chunk 1107
Chunk 1108
Chunk 1109
Chunk 1110
Chunk 1111
Chunk 1112
Chunk 1113
Chunk 1114
Chunk 1115
Chunk 1116
Chunk 1117
Chunk 1118
Chunk 1119
Chunk 1120
Chunk 1121
Chunk 1122
Chunk 1123
Chunk 1124
Chunk 1125
Chunk 1126
Chunk 1127
Chunk 1128
Chunk 1129
Chunk 1130
Chunk 1131
Chunk 1132
Chunk 1133
Chunk 1134
Chunk 1135
Chunk 1136
Chunk 1137
Chunk 1138
Chunk 1139
Chunk 1140
Chunk 1141
Chunk 1142
Chunk 1143
Chunk 1144
Chunk 1145
Chunk 1146
Chunk 1147
Chunk 1148
Chunk 1149
Chunk 1150
Chunk 1151
Chunk 1152
Chunk 1153
Chunk 1154
Chunk 1155
Chunk 1156
Chunk 1157
Chunk 1158
Chunk 1159
Chunk 1160
Chunk 1161
Chunk 1162
Chunk 1163
Chunk 1164
Chunk 1165
Chunk 1166
Chunk 1167
Chunk 1168
Chunk 1169
Chunk 1170
Chunk 1171
Chunk 1172
Chunk 1173
Chunk 1174
Chunk 1175
Chunk 1176
Chunk 1177
Chunk 1178
Chunk 1179
Chunk 1180
Chunk 1181
Chunk 1182
Chunk 1183
Chunk 1184
Chunk 1185
Chunk 1186
Chunk 1187
Chunk 1188
Chunk 1189
Chunk 1190
Chunk 1191
Chunk 1192
Chunk 1193
Chunk 1194
Chunk 1195
Chunk 1196
Chunk 1197
Chunk 1198
Chunk 1199
Chunk 1200
Chunk 1201
Chunk 1202
Chunk 1203
Chunk 1204
Chunk 1205
Chunk 1206
Chunk 1207
Chunk 1208
Chunk 1209
Chunk 1210
Chunk 1211
Chunk 1212
Chunk 1213
Chunk 1214
Chunk 1215
Chunk 1216
Chunk 1217
Chunk 1218
Chunk 1219
Chunk 1220
Chunk 1221
Chunk 1222
Chunk 1223
Chunk 1224
Chunk 1225
Chunk 1226
Chunk 1227
Chunk 1228
Chunk 1229
Chunk 1230
Chunk 1231
Chunk 1232
Chunk 1233
Chunk 1234
Chunk 1235
Chunk 1236
Chunk 1237
Chunk 1238
Chunk 1239
Chunk 1240
Chunk 1241
Chunk 1242
Chunk 1243
Chunk 1244
Chunk 1245
Chunk 1246
Chunk 1247
Chunk 1248
Chunk 1249
Chunk 1250
Chunk 1251
Chunk 1252
Chunk 1253
Chunk 1254
Chunk 1255
Chunk 1256
Chunk 1257
Chunk 1258
Chunk 1259
Chunk 1260
Chunk 1261
Chunk 1262
Chunk 1263
Chunk 1264
Chunk 1265
Chunk 1266
Chunk 1267
Chunk 1268
Chunk 1269
Chunk 1270
Chunk 1271
Chunk 1272
Chunk 1273
Chunk 1274
Chunk 1275
Chunk 1276
Chunk 1277
Chunk 1278
Chunk 1279
Chunk 1280
Chunk 1281
Chunk 1282
Chunk 1283
Chunk 1284
Chunk 1285
Chunk 1286
Chunk 1287
Chunk 1288
Chunk 1289
Chunk 1290
Chunk 1291
Chunk 1292
Chunk 1293
Chunk 1294
Chunk 1295
Chunk 1296
Chunk 1297
Chunk 1298
Chunk 1299
Chunk 1300
Chunk 1301
Chunk 1302
Chunk 1303
Chunk 1304
Chunk 1305
Chunk 1306
Chunk 1307
Chunk 1308
Chunk 1309
Chunk 1310
Chunk 1311
Chunk 1312
Chunk 1313
Chunk 1314
Chunk 1315
Chunk 1316
Chunk 1317
Chunk 1318
Chunk 1319
Chunk 1320
Chunk 1321
Chunk 1322
Chunk 1323
Chunk 1324
Chunk 1325
Chunk 1326
Chunk 1327
Chunk 1328
Chunk 1329
Chunk 1330
Chunk 1331
Chunk 1332
Chunk 1333
Chunk 1334
Chunk 1335
Chunk 1336
Chunk 1337
Chunk 1338
Chunk 1339
Chunk 1340
Chunk 1341
Chunk 1342
Chunk 1343
Chunk 1344
Chunk 1345
Chunk 1346
Chunk 1347
Chunk 1348
Chunk 1349
Chunk 1350
Chunk 1351
Chunk 1352
Chunk 1353
Chunk 1354
Chunk 1355
Chunk 1356
Chunk 1357
Chunk 1358
Chunk 1359
Chunk 1360
Chunk 1361
Chunk 1362
Chunk 1363
Chunk 1364
Chunk 1365
Chunk 1366
Chunk 1367
Chunk 1368
Chunk 1369
Chunk 1370
Chunk 1371
Chunk 1372
Chunk 1373
Chunk 1374
Chunk 1375
Chunk 1376
Chunk 1377
Chunk 1378
Chunk 1379
Chunk 1380
Chunk 1381
Chunk 1382
Chunk 1383
Chunk 1384
Chunk 1385
Chunk 1386
Chunk 1387
Chunk 1388
Chunk 1389
Chunk 1390
Chunk 1391
Chunk 1392
Chunk 1393
Chunk 1394
Chunk 1395
Chunk 1396
Chunk 1397
Chunk 1398
Chunk 1399
Chunk 1400
Chunk 1401
Chunk 1402
Chunk 1403
Chunk 1404
Chunk 1405
Chunk 1406
Chunk 1407
Chunk 1408
Chunk 1409
Chunk 1410
Chunk 1411
Chunk 1412
Chunk 1413
Chunk 1414
Chunk 1415
Chunk 1416
Chunk 1417
Chunk 1418
Chunk 1419
Chunk 1420
Chunk 1421
Chunk 1422
Chunk 1423
Chunk 1424
Chunk 1425
Chunk 1426
Chunk 1427
Chunk 1428
Chunk 1429
Chunk 1430
Chunk 1431
Chunk 1432
Chunk 1433
Chunk 1434
Chunk 1435
Chunk 1436
Chunk 1437
Chunk 1438
Chunk 1439
Chunk 1440
Chunk 1441
Chunk 1442
Chunk 1443
Chunk 1444
Chunk 1445
Chunk 1446
Chunk 1447
Chunk 1448
Chunk 1449
Chunk 1450
Chunk 1451
Chunk 1452
Chunk 1453
Chunk 1454
Chunk 1455
Chunk 1456
Chunk 1457
Chunk 1458
Chunk 1459
Chunk 1460
Chunk 1461
Chunk 1462
Chunk 1463
Chunk 1464
Chunk 1465
Chunk 1466
Chunk 1467
Chunk 1468
Chunk 1469
Chunk 1470
Chunk 1471
Chunk 1472
Chunk 1473
Chunk 1474
Chunk 1475
Chunk 1476
Chunk 1477
Chunk 1478
Chunk 1479
Chunk 1480
Chunk 1481
Chunk 1482
Chunk 1483
Chunk 1484
Chunk 1485
Chunk 1486
Chunk 1487
Chunk 1488
Chunk 1489
Chunk 1490
Chunk 1491
Chunk 1492
Chunk 1493
Chunk 1494
Chunk 1495
Chunk 1496
Chunk 1497
Chunk 1498
Chunk 1499
Chunk 1500
Chunk 1501
Chunk 1502
Chunk 1503
Chunk 1504
Chunk 1505
Chunk 1506
Chunk 1507
Chunk 1508
Chunk 1509
Chunk 1510
Chunk 1511
Chunk 1512
Chunk 1513
Chunk 1514
Chunk 1515
Chunk 1516
Chunk 1517
Chunk 1518
Chunk 1519
Chunk 1520
Chunk 1521
Chunk 1522
Chunk 1523
Chunk 1524
Chunk 1525
Chunk 1526
Chunk 1527
Chunk 1528
Chunk 1529
Chunk 1530
Chunk 1531
Chunk 1532
Chunk 1533
Chunk 1534
Chunk 1535
Chunk 1536
Chunk 1537
Chunk 1538
Chunk 1539
Chunk 1540
Chunk 1541
Chunk 1542
Chunk 1543
Chunk 1544
Chunk 1545
Chunk 1546
Chunk 1547
Chunk 1548
Chunk 1549
Chunk 1550
Chunk 1551
Chunk 1552
Chunk 1553
Chunk 1554
Chunk 1555
Chunk 1556
Chunk 1557
Chunk 1558
Chunk 1559
Chunk 1560
Chunk 1561
Chunk 1562
Chunk 1563
Chunk 1564
Chunk 1565
Chunk 1566
Chunk 1567
Chunk 1568
Chunk 1569
Chunk 1570
Chunk 1571
Chunk 1572
Chunk 1573
Chunk 1574
Chunk 1575
Chunk 1576
Chunk 1577
Chunk 1578
Chunk 1579
Chunk 1580
Chunk 1581
Chunk 1582
Chunk 1583
Chunk 1584
Chunk 1585
Chunk 1586
Chunk 1587
Chunk 1588
Chunk 1589
Chunk 1590
Chunk 1591
Chunk 1592
Chunk 1593
Chunk 1594
Chunk 1595
Chunk 1596
Chunk 1597
Chunk 1598
Chunk 1599
Chunk 1600
Chunk 1601
Chunk 1602
Chunk 1603
Chunk 1604
Chunk 1605
Chunk 1606
Chunk 1607
Chunk 1608
Chunk 1609
Chunk 1610
Chunk 1611
Chunk 1612
Chunk 1613
Chunk 1614
Chunk 1615
Chunk 1616
Chunk 1617
Chunk 1618
Chunk 1619
Chunk 1620
Chunk 1621
Chunk 1622
Chunk 1623
Chunk 1624
Chunk 1625
Chunk 1626
Chunk 1627
Chunk 1628
Chunk 1629
Chunk 1630
Chunk 1631
Chunk 1632
Chunk 1633
Chunk 1634
Chunk 1635
Chunk 1636
Chunk 1637
Chunk 1638
Chunk 1639
Chunk 1640
Chunk 1641
Chunk 1642
Chunk 1643
Chunk 1644
Chunk 1645
Chunk 1646
Chunk 1647
Chunk 1648
Chunk 1649
Chunk 1650
Chunk 1651
Chunk 1652
Chunk 1653
Chunk 1654
Chunk 1655
Chunk 1656
Chunk 1657
Chunk 1658
Chunk 1659
Chunk 1660
Chunk 1661
Chunk 1662
Chunk 1663
Chunk 1664
Chunk 1665
Chunk 1666
Chunk 1667
Chunk 1668
Chunk 1669
Chunk 1670
Chunk 1671
Chunk 1672
Chunk 1673
Chunk 1674
Chunk 1675
Chunk 1676
Chunk 1677
Chunk 1678
Chunk 1679
Chunk 1680
Chunk 1681
Chunk 1682
Chunk 1683
Chunk 1684
Chunk 1685
Chunk 1686
Chunk 1687
Chunk 1688
Chunk 1689
Chunk 1690
Chunk 1691
Chunk 1692
Chunk 1693
Chunk 1694
Chunk 1695
Chunk 1696
Chunk 1697
Chunk 1698
Chunk 1699
Chunk 1700
Chunk 1701
Chunk 1702
Chunk 1703
Chunk 1704
Chunk 1705
Chunk 1706
Chunk 1707
Chunk 1708
Chunk 1709
Chunk 1710
Chunk 1711
Chunk 1712
Chunk 1713
Chunk 1714
Chunk 1715
Chunk 1716
Chunk 1717
Chunk 1718
Chunk 1719
Chunk 1720
Chunk 1721
Chunk 1722
Chunk 1723
Chunk 1724
Chunk 1725
Chunk 1726
Chunk 1727
Chunk 1728
Chunk 1729
Chunk 1730
Chunk 1731
Chunk 1732
Chunk 1733
Chunk 1734
Chunk 1735
Chunk 1736
Chunk 1737
Chunk 1738
Chunk 1739
Chunk 1740
Chunk 1741
Chunk 1742
Chunk 1743
Chunk 1744
Chunk 1745
Chunk 1746
Chunk 1747
Chunk 1748
Chunk 1749
Chunk 1750
Chunk 1751
Chunk 1752
Chunk 1753
Chunk 1754
Chunk 1755
Chunk 1756
Chunk 1757
Chunk 1758
Chunk 1759
Chunk 1760
Chunk 1761
Chunk 1762
Chunk 1763
Chunk 1764
Chunk 1765
Chunk 1766
Chunk 1767
Chunk 1768
Chunk 1769
Chunk 1770
Chunk 1771
Chunk 1772
Chunk 1773
Chunk 1774
Chunk 1775
Chunk 1776
Chunk 1777
Chunk 1778
Chunk 1779
Chunk 1780
Chunk 1781
Chunk 1782
Chunk 1783
Chunk 1784
Chunk 1785
Chunk 1786
Chunk 1787
Chunk 1788
Chunk 1789
Chunk 1790
Chunk 1791
Chunk 1792
Chunk 1793
Chunk 1794
Chunk 1795
Chunk 1796
Chunk 1797
Chunk 1798
Chunk 1799
Chunk 1800
Chunk 1801
Chunk 1802
Chunk 1803
Chunk 1804
Chunk 1805
Chunk 1806
Chunk 1807
Chunk 1808
Chunk 1809
Chunk 1810
Chunk 1811
Chunk 1812
Chunk 1813
Chunk 1814
Chunk 1815
Chunk 1816
Chunk 1817
Chunk 1818
Chunk 1819
Chunk 1820
Chunk 1821
Chunk 1822
Chunk 1823
Chunk 1824
Chunk 1825
Chunk 1826
Chunk 1827
Chunk 1828
Chunk 1829
Chunk 1830
Chunk 1831
Chunk 1832
Chunk 1833
Chunk 1834
Chunk 1835
Chunk 1836
Chunk 1837
Chunk 1838
Chunk 1839
Chunk 1840
Chunk 1841
Chunk 1842
Chunk 1843
Chunk 1844
Chunk 1845
Chunk 1846
Chunk 1847
Chunk 1848
Chunk 1849
Chunk 1850
Chunk 1851
Chunk 1852
Chunk 1853
Chunk 1854
Chunk 1855
Chunk 1856
Chunk 1857
Chunk 1858
Chunk 1859
Chunk 1860
Chunk 1861
Chunk 1862
Chunk 1863
Chunk 1864
Chunk 1865
Chunk 1866
Chunk 1867
Chunk 1868
Chunk 1869
Chunk 1870
Chunk 1871
Chunk 1872
Chunk 1873
Chunk 1874
Chunk 1875
Chunk 1876
Chunk 1877
Chunk 1878
Chunk 1879
Chunk 1880
Chunk 1881
Chunk 1882
Chunk 1883
Chunk 1884
Chunk 1885
Chunk 1886
Chunk 1887
Chunk 1888
Chunk 1889
Chunk 1890
Chunk 1891
Chunk 1892
Chunk 1893
Chunk 1894
Chunk 1895
Chunk 1896
Chunk 1897
Chunk 1898
Chunk 1899
Chunk 1900
Chunk 1901
Chunk 1902
Chunk 1903
Chunk 1904
Chunk 1905
Chunk 1906
Chunk 1907
Chunk 1908
Chunk 1909
Chunk 1910
Chunk 1911
Chunk 1912
Chunk 1913
Chunk 1914
Chunk 1915
Chunk 1916
Chunk 1917
Chunk 1918

In [64]:
parquet_schema_old = pa.Table.from_pandas(df=chunk).schema
parquet_schema_new = pa.schema([
    ('기준_날짜', pa.int64()),
    ('집계_기준', pa.string()),
    ('기준_시간대', pa.float64()),
    ('시작_대여소_ID', pa.string()),
    ('시작_대여소명', pa.string()),
    ('종료_대여소_ID', pa.string()),
    ('종료_대여소명', pa.string()),
    ('전체_건수', pa.int8()),
    ('전체_이용_분', pa.int16()),
    ('전체_이용_거리', pa.int32()),
    
])
parquet_schema_old == parquet_schema_new
chunksize = 500
csv_stream = pd.read_csv(csv_file, sep=',', chunksize=chunksize, low_memory=False)
for i, chunk in enumerate(csv_stream):
    print("Chunk", i)
    if i == 0:
        # Guess the schema of the CSV file from the first chunk
        parquet_schema = parquet_schema_new
        # Open a Parquet file for writing
        parquet_writer = pq.ParquetWriter(parquet_file, parquet_schema, compression='zstd')
    # Write CSV chunk to the parquet file
    table = pa.Table.from_pandas(chunk, schema=parquet_schema)
    parquet_writer.write_table(table)
else :
    parquet_writer.close()

Chunk 0
Chunk 1
Chunk 2
Chunk 3
Chunk 4
Chunk 5
Chunk 6
Chunk 7
Chunk 8
Chunk 9
Chunk 10
Chunk 11
Chunk 12
Chunk 13
Chunk 14
Chunk 15
Chunk 16
Chunk 17
Chunk 18
Chunk 19
Chunk 20
Chunk 21
Chunk 22
Chunk 23
Chunk 24
Chunk 25
Chunk 26
Chunk 27
Chunk 28
Chunk 29
Chunk 30
Chunk 31
Chunk 32
Chunk 33
Chunk 34
Chunk 35
Chunk 36
Chunk 37
Chunk 38
Chunk 39
Chunk 40
Chunk 41
Chunk 42
Chunk 43
Chunk 44
Chunk 45
Chunk 46
Chunk 47
Chunk 48
Chunk 49
Chunk 50
Chunk 51
Chunk 52
Chunk 53
Chunk 54
Chunk 55
Chunk 56
Chunk 57
Chunk 58
Chunk 59
Chunk 60
Chunk 61
Chunk 62
Chunk 63
Chunk 64
Chunk 65
Chunk 66
Chunk 67
Chunk 68
Chunk 69
Chunk 70
Chunk 71
Chunk 72
Chunk 73
Chunk 74
Chunk 75
Chunk 76
Chunk 77
Chunk 78
Chunk 79
Chunk 80
Chunk 81
Chunk 82
Chunk 83
Chunk 84
Chunk 85
Chunk 86
Chunk 87
Chunk 88
Chunk 89
Chunk 90
Chunk 91
Chunk 92
Chunk 93
Chunk 94
Chunk 95
Chunk 96
Chunk 97
Chunk 98
Chunk 99
Chunk 100
Chunk 101
Chunk 102
Chunk 103
Chunk 104
Chunk 105
Chunk 106
Chunk 107
Chunk 108
Chunk 109
Chunk 110
Chunk 111
Chunk 112
Chunk 113
Chunk 114
Chunk 115
Chunk 116
Chunk 117
Chunk 118
Chunk 119
Chunk 120
Chunk 121
Chunk 122
Chunk 123
Chunk 124
Chunk 125
Chunk 126
Chunk 127
Chunk 128
Chunk 129
Chunk 130
Chunk 131
Chunk 132
Chunk 133
Chunk 134
Chunk 135
Chunk 136
Chunk 137
Chunk 138
Chunk 139
Chunk 140
Chunk 141
Chunk 142
Chunk 143
Chunk 144
Chunk 145
Chunk 146
Chunk 147
Chunk 148
Chunk 149
Chunk 150
Chunk 151
Chunk 152
Chunk 153
Chunk 154
Chunk 155
Chunk 156
Chunk 157
Chunk 158
Chunk 159
Chunk 160
Chunk 161
Chunk 162
Chunk 163
Chunk 164
Chunk 165
Chunk 166
Chunk 167
Chunk 168
Chunk 169
Chunk 170
Chunk 171
Chunk 172
Chunk 173
Chunk 174
Chunk 175
Chunk 176
Chunk 177
Chunk 178
Chunk 179
Chunk 180
Chunk 181
Chunk 182
Chunk 183
Chunk 184
Chunk 185
Chunk 186
Chunk 187
Chunk 188
Chunk 189
Chunk 190
Chunk 191
Chunk 192
Chunk 193
Chunk 194
Chunk 195
Chunk 196
Chunk 197
Chunk 198
Chunk 199
Chunk 200
Chunk 201
Chunk 202
Chunk 203
Chunk 204
Chunk 205
Chunk 206
Chunk 207
Chunk 208
Chunk 209
Chunk 210
Chunk 211
Chunk 212
Chunk 213
Chunk 214
Chunk 215
Chunk 216
Chunk 217
Chunk 218
Chunk 219
Chunk 220
Chunk 221
Chunk 222
Chunk 223
Chunk 224
Chunk 225
Chunk 226
Chunk 227
Chunk 228
Chunk 229
Chunk 230
Chunk 231
Chunk 232
Chunk 233
Chunk 234
Chunk 235
Chunk 236
Chunk 237
Chunk 238
Chunk 239
Chunk 240
Chunk 241
Chunk 242
Chunk 243
Chunk 244
Chunk 245
Chunk 246
Chunk 247
Chunk 248
Chunk 249
Chunk 250
Chunk 251
Chunk 252
Chunk 253
Chunk 254
Chunk 255
Chunk 256
Chunk 257
Chunk 258
Chunk 259
Chunk 260
Chunk 261
Chunk 262
Chunk 263
Chunk 264
Chunk 265
Chunk 266
Chunk 267
Chunk 268
Chunk 269
Chunk 270
Chunk 271
Chunk 272
Chunk 273
Chunk 274
Chunk 275
Chunk 276
Chunk 277
Chunk 278
Chunk 279
Chunk 280
Chunk 281
Chunk 282
Chunk 283
Chunk 284
Chunk 285
Chunk 286
Chunk 287
Chunk 288
Chunk 289
Chunk 290
Chunk 291
Chunk 292
Chunk 293
Chunk 294
Chunk 295
Chunk 296
Chunk 297
Chunk 298
Chunk 299
Chunk 300
Chunk 301
Chunk 302
Chunk 303
Chunk 304
Chunk 305
Chunk 306
Chunk 307
Chunk 308
Chunk 309
Chunk 310
Chunk 311
Chunk 312
Chunk 313
Chunk 314
Chunk 315
Chunk 316
Chunk 317
Chunk 318
Chunk 319
Chunk 320
Chunk 321
Chunk 322
Chunk 323
Chunk 324
Chunk 325
Chunk 326
Chunk 327
Chunk 328
Chunk 329
Chunk 330
Chunk 331
Chunk 332
Chunk 333
Chunk 334
Chunk 335
Chunk 336
Chunk 337
Chunk 338
Chunk 339
Chunk 340
Chunk 341
Chunk 342
Chunk 343
Chunk 344
Chunk 345
Chunk 346
Chunk 347
Chunk 348
Chunk 349
Chunk 350
Chunk 351
Chunk 352
Chunk 353
Chunk 354
Chunk 355
Chunk 356
Chunk 357
Chunk 358
Chunk 359
Chunk 360
Chunk 361
Chunk 362
Chunk 363
Chunk 364
Chunk 365
Chunk 366
Chunk 367
Chunk 368
Chunk 369
Chunk 370
Chunk 371
Chunk 372
Chunk 373
Chunk 374
Chunk 375
Chunk 376
Chunk 377
Chunk 378
Chunk 379
Chunk 380
Chunk 381
Chunk 382
Chunk 383
Chunk 384
Chunk 385
Chunk 386
Chunk 387
Chunk 388
Chunk 389
Chunk 390
Chunk 391
Chunk 392
Chunk 393
Chunk 394
Chunk 395
Chunk 396
Chunk 397
Chunk 398
Chunk 399
Chunk 400
Chunk 401
Chunk 402
Chunk 403
Chunk 404
Chunk 405
Chunk 406
Chunk 407
Chunk 408
Chunk 409
Chunk 410
Chunk 411
Chunk 412
Chunk 413
Chunk 414
Chunk 415
Chunk 416
Chunk 417
Chunk 418
Chunk 419
Chunk 420
Chunk 421
Chunk 422
Chunk 423
Chunk 424
Chunk 425
Chunk 426
Chunk 427
Chunk 428
Chunk 429
Chunk 430
Chunk 431
Chunk 432
Chunk 433
Chunk 434
Chunk 435
Chunk 436
Chunk 437
Chunk 438
Chunk 439
Chunk 440
Chunk 441
Chunk 442
Chunk 443
Chunk 444
Chunk 445
Chunk 446
Chunk 447
Chunk 448
Chunk 449
Chunk 450
Chunk 451
Chunk 452
Chunk 453
Chunk 454
Chunk 455
Chunk 456
Chunk 457
Chunk 458
Chunk 459
Chunk 460
Chunk 461
Chunk 462
Chunk 463
Chunk 464
Chunk 465
Chunk 466
Chunk 467
Chunk 468
Chunk 469
Chunk 470
Chunk 471
Chunk 472
Chunk 473
Chunk 474
Chunk 475
Chunk 476
Chunk 477
Chunk 478
Chunk 479
Chunk 480
Chunk 481
Chunk 482
Chunk 483
Chunk 484
Chunk 485
Chunk 486
Chunk 487
Chunk 488
Chunk 489
Chunk 490
Chunk 491
Chunk 492
Chunk 493
Chunk 494
Chunk 495
Chunk 496
Chunk 497
Chunk 498
Chunk 499
Chunk 500
Chunk 501
Chunk 502
Chunk 503
Chunk 504
Chunk 505
Chunk 506
Chunk 507
Chunk 508
Chunk 509
Chunk 510
Chunk 511
Chunk 512
Chunk 513
Chunk 514
Chunk 515
Chunk 516
Chunk 517
Chunk 518
Chunk 519
Chunk 520
Chunk 521
Chunk 522
Chunk 523
Chunk 524
Chunk 525
Chunk 526
Chunk 527
Chunk 528
Chunk 529
Chunk 530
Chunk 531
Chunk 532
Chunk 533
Chunk 534
Chunk 535
Chunk 536
Chunk 537
Chunk 538
Chunk 539
Chunk 540
Chunk 541
Chunk 542
Chunk 543
Chunk 544
Chunk 545
Chunk 546
Chunk 547
Chunk 548
Chunk 549
Chunk 550
Chunk 551
Chunk 552
Chunk 553
Chunk 554
Chunk 555
Chunk 556
Chunk 557
Chunk 558
Chunk 559
Chunk 560
Chunk 561
Chunk 562
Chunk 563
Chunk 564
Chunk 565
Chunk 566
Chunk 567
Chunk 568
Chunk 569
Chunk 570
Chunk 571
Chunk 572
Chunk 573
Chunk 574
Chunk 575
Chunk 576
Chunk 577
Chunk 578
Chunk 579
Chunk 580
Chunk 581
Chunk 582
Chunk 583
Chunk 584
Chunk 585
Chunk 586
Chunk 587
Chunk 588
Chunk 589
Chunk 590
Chunk 591
Chunk 592
Chunk 593
Chunk 594
Chunk 595
Chunk 596
Chunk 597
Chunk 598
Chunk 599
Chunk 600
Chunk 601
Chunk 602
Chunk 603
Chunk 604
Chunk 605
Chunk 606
Chunk 607
Chunk 608
Chunk 609
Chunk 610
Chunk 611
Chunk 612
Chunk 613
Chunk 614
Chunk 615
Chunk 616
Chunk 617
Chunk 618
Chunk 619
Chunk 620
Chunk 621
Chunk 622
Chunk 623
Chunk 624
Chunk 625
Chunk 626
Chunk 627
Chunk 628
Chunk 629
Chunk 630
Chunk 631
Chunk 632
Chunk 633
Chunk 634
Chunk 635
Chunk 636
Chunk 637
Chunk 638
Chunk 639
Chunk 640
Chunk 641
Chunk 642
Chunk 643
Chunk 644
Chunk 645
Chunk 646
Chunk 647
Chunk 648
Chunk 649
Chunk 650
Chunk 651
Chunk 652
Chunk 653
Chunk 654
Chunk 655
Chunk 656
Chunk 657
Chunk 658
Chunk 659
Chunk 660
Chunk 661
Chunk 662
Chunk 663
Chunk 664
Chunk 665
Chunk 666
Chunk 667
Chunk 668
Chunk 669
Chunk 670
Chunk 671
Chunk 672
Chunk 673
Chunk 674
Chunk 675
Chunk 676
Chunk 677
Chunk 678
Chunk 679
Chunk 680
Chunk 681
Chunk 682
Chunk 683
Chunk 684
Chunk 685
Chunk 686
Chunk 687
Chunk 688
Chunk 689
Chunk 690
Chunk 691
Chunk 692
Chunk 693
Chunk 694
Chunk 695
Chunk 696
Chunk 697
Chunk 698
Chunk 699
Chunk 700
Chunk 701
Chunk 702
Chunk 703
Chunk 704
Chunk 705
Chunk 706
Chunk 707
Chunk 708
Chunk 709
Chunk 710
Chunk 711
Chunk 712
Chunk 713
Chunk 714
Chunk 715
Chunk 716
Chunk 717
Chunk 718
Chunk 719
Chunk 720
Chunk 721
Chunk 722
Chunk 723
Chunk 724
Chunk 725
Chunk 726
Chunk 727
Chunk 728
Chunk 729
Chunk 730
Chunk 731
Chunk 732
Chunk 733
Chunk 734
Chunk 735
Chunk 736
Chunk 737
Chunk 738
Chunk 739
Chunk 740
Chunk 741
Chunk 742
Chunk 743
Chunk 744
Chunk 745
Chunk 746
Chunk 747
Chunk 748
Chunk 749
Chunk 750
Chunk 751
Chunk 752
Chunk 753
Chunk 754
Chunk 755
Chunk 756
Chunk 757
Chunk 758
Chunk 759
Chunk 760
Chunk 761
Chunk 762
Chunk 763
Chunk 764
Chunk 765
Chunk 766
Chunk 767
Chunk 768
Chunk 769
Chunk 770
Chunk 771
Chunk 772
Chunk 773
Chunk 774
Chunk 775
Chunk 776
Chunk 777
Chunk 778
Chunk 779
Chunk 780
Chunk 781
Chunk 782
Chunk 783
Chunk 784
Chunk 785
Chunk 786
Chunk 787
Chunk 788
Chunk 789
Chunk 790
Chunk 791
Chunk 792
Chunk 793
Chunk 794
Chunk 795
Chunk 796
Chunk 797
Chunk 798
Chunk 799
Chunk 800
Chunk 801
Chunk 802
Chunk 803
Chunk 804
Chunk 805
Chunk 806
Chunk 807
Chunk 808
Chunk 809
Chunk 810
Chunk 811
Chunk 812
Chunk 813
Chunk 814
Chunk 815
Chunk 816
Chunk 817
Chunk 818
Chunk 819
Chunk 820
Chunk 821
Chunk 822
Chunk 823
Chunk 824
Chunk 825
Chunk 826
Chunk 827
Chunk 828
Chunk 829
Chunk 830
Chunk 831
Chunk 832
Chunk 833
Chunk 834
Chunk 835
Chunk 836
Chunk 837
Chunk 838
Chunk 839
Chunk 840
Chunk 841
Chunk 842
Chunk 843
Chunk 844
Chunk 845
Chunk 846
Chunk 847
Chunk 848
Chunk 849
Chunk 850
Chunk 851
Chunk 852
Chunk 853
Chunk 854
Chunk 855
Chunk 856
Chunk 857
Chunk 858
Chunk 859
Chunk 860
Chunk 861
Chunk 862
Chunk 863
Chunk 864
Chunk 865
Chunk 866
Chunk 867
Chunk 868
Chunk 869
Chunk 870
Chunk 871
Chunk 872
Chunk 873
Chunk 874
Chunk 875
Chunk 876
Chunk 877
Chunk 878
Chunk 879
Chunk 880
Chunk 881
Chunk 882
Chunk 883
Chunk 884
Chunk 885
Chunk 886
Chunk 887
Chunk 888
Chunk 889
Chunk 890
Chunk 891
Chunk 892
Chunk 893
Chunk 894
Chunk 895
Chunk 896
Chunk 897
Chunk 898
Chunk 899
Chunk 900
Chunk 901
Chunk 902
Chunk 903
Chunk 904
Chunk 905
Chunk 906
Chunk 907
Chunk 908
Chunk 909
Chunk 910
Chunk 911
Chunk 912
Chunk 913
Chunk 914
Chunk 915
Chunk 916
Chunk 917
Chunk 918
Chunk 919
Chunk 920
Chunk 921
Chunk 922
Chunk 923
Chunk 924
Chunk 925
Chunk 926
Chunk 927
Chunk 928
Chunk 929
Chunk 930
Chunk 931
Chunk 932
Chunk 933
Chunk 934
Chunk 935
Chunk 936
Chunk 937
Chunk 938
Chunk 939
Chunk 940
Chunk 941
Chunk 942
Chunk 943
Chunk 944
Chunk 945
Chunk 946
Chunk 947
Chunk 948
Chunk 949
Chunk 950
Chunk 951
Chunk 952
Chunk 953
Chunk 954
Chunk 955
Chunk 956
Chunk 957
Chunk 958
Chunk 959
Chunk 960
Chunk 961
Chunk 962
Chunk 963
Chunk 964
Chunk 965
Chunk 966
Chunk 967
Chunk 968
Chunk 969
Chunk 970
Chunk 971
Chunk 972
Chunk 973
Chunk 974
Chunk 975
Chunk 976
Chunk 977
Chunk 978
Chunk 979
Chunk 980
Chunk 981
Chunk 982
Chunk 983
Chunk 984
Chunk 985
Chunk 986
Chunk 987
Chunk 988
Chunk 989
Chunk 990
Chunk 991
Chunk 992
Chunk 993
Chunk 994
Chunk 995
Chunk 996
Chunk 997
Chunk 998
Chunk 999
Chunk 1000
Chunk 1001
Chunk 1002
Chunk 1003
Chunk 1004
Chunk 1005
Chunk 1006
Chunk 1007
Chunk 1008
Chunk 1009
Chunk 1010
Chunk 1011
Chunk 1012
Chunk 1013
Chunk 1014
Chunk 1015
Chunk 1016
Chunk 1017
Chunk 1018
Chunk 1019
Chunk 1020
Chunk 1021
Chunk 1022
Chunk 1023
Chunk 1024
Chunk 1025
Chunk 1026
Chunk 1027
Chunk 1028
Chunk 1029
Chunk 1030
Chunk 1031
Chunk 1032
Chunk 1033
Chunk 1034
Chunk 1035
Chunk 1036
Chunk 1037
Chunk 1038
Chunk 1039
Chunk 1040
Chunk 1041
Chunk 1042
Chunk 1043
Chunk 1044
Chunk 1045
Chunk 1046
Chunk 1047
Chunk 1048
Chunk 1049
Chunk 1050
Chunk 1051
Chunk 1052
Chunk 1053
Chunk 1054
Chunk 1055
Chunk 1056
Chunk 1057
Chunk 1058
Chunk 1059
Chunk 1060
Chunk 1061
Chunk 1062
Chunk 1063
Chunk 1064
Chunk 1065
Chunk 1066
Chunk 1067
Chunk 1068
Chunk 1069
Chunk 1070
Chunk 1071
Chunk 1072
Chunk 1073
Chunk 1074
Chunk 1075
Chunk 1076
Chunk 1077
Chunk 1078
Chunk 1079
Chunk 1080
Chunk 1081
Chunk 1082
Chunk 1083
Chunk 1084
Chunk 1085
Chunk 1086
Chunk 1087
Chunk 1088
Chunk 1089
Chunk 1090
Chunk 1091
Chunk 1092
Chunk 1093
Chunk 1094
Chunk 1095
Chunk 1096
Chunk 1097
Chunk 1098
Chunk 1099
Chunk 1100
Chunk 1101
Chunk 1102
Chunk 1103
Chunk 1104
Chunk 1105
Chunk 1106
Chunk 1107
Chunk 1108
Chunk 1109
Chunk 1110
Chunk 1111
Chunk 1112
Chunk 1113
Chunk 1114
Chunk 1115
Chunk 1116
Chunk 1117
Chunk 1118
Chunk 1119
Chunk 1120
Chunk 1121
Chunk 1122
Chunk 1123
Chunk 1124
Chunk 1125
Chunk 1126
Chunk 1127
Chunk 1128
Chunk 1129
Chunk 1130
Chunk 1131
Chunk 1132
Chunk 1133
Chunk 1134
Chunk 1135
Chunk 1136
Chunk 1137
Chunk 1138
Chunk 1139
Chunk 1140
Chunk 1141
Chunk 1142
Chunk 1143
Chunk 1144
Chunk 1145
Chunk 1146
Chunk 1147
Chunk 1148
Chunk 1149
Chunk 1150
Chunk 1151
Chunk 1152
Chunk 1153
Chunk 1154
Chunk 1155
Chunk 1156
Chunk 1157
Chunk 1158
Chunk 1159
Chunk 1160
Chunk 1161
Chunk 1162
Chunk 1163
Chunk 1164
Chunk 1165
Chunk 1166
Chunk 1167
Chunk 1168
Chunk 1169
Chunk 1170
Chunk 1171
Chunk 1172
Chunk 1173
Chunk 1174
Chunk 1175
Chunk 1176
Chunk 1177
Chunk 1178
Chunk 1179
Chunk 1180
Chunk 1181
Chunk 1182
Chunk 1183
Chunk 1184
Chunk 1185
Chunk 1186
Chunk 1187
Chunk 1188
Chunk 1189
Chunk 1190
Chunk 1191
Chunk 1192
Chunk 1193
Chunk 1194
Chunk 1195
Chunk 1196
Chunk 1197
Chunk 1198
Chunk 1199
Chunk 1200
Chunk 1201
Chunk 1202
Chunk 1203
Chunk 1204
Chunk 1205
Chunk 1206
Chunk 1207
Chunk 1208
Chunk 1209
Chunk 1210
Chunk 1211
Chunk 1212
Chunk 1213
Chunk 1214
Chunk 1215
Chunk 1216
Chunk 1217
Chunk 1218
Chunk 1219
Chunk 1220
Chunk 1221
Chunk 1222
Chunk 1223
Chunk 1224
Chunk 1225
Chunk 1226
Chunk 1227
Chunk 1228
Chunk 1229
Chunk 1230
Chunk 1231
Chunk 1232
Chunk 1233
Chunk 1234
Chunk 1235
Chunk 1236
Chunk 1237
Chunk 1238
Chunk 1239
Chunk 1240
Chunk 1241
Chunk 1242
Chunk 1243
Chunk 1244
Chunk 1245
Chunk 1246
Chunk 1247
Chunk 1248
Chunk 1249
Chunk 1250
Chunk 1251
Chunk 1252
Chunk 1253
Chunk 1254
Chunk 1255
Chunk 1256
Chunk 1257
Chunk 1258
Chunk 1259
Chunk 1260
Chunk 1261
Chunk 1262
Chunk 1263
Chunk 1264
Chunk 1265
Chunk 1266
Chunk 1267
Chunk 1268
Chunk 1269
Chunk 1270
Chunk 1271
Chunk 1272
Chunk 1273
Chunk 1274
Chunk 1275
Chunk 1276
Chunk 1277
Chunk 1278
Chunk 1279
Chunk 1280
Chunk 1281
Chunk 1282
Chunk 1283
Chunk 1284
Chunk 1285
Chunk 1286
Chunk 1287
Chunk 1288
Chunk 1289
Chunk 1290
Chunk 1291
Chunk 1292
Chunk 1293
Chunk 1294
Chunk 1295
Chunk 1296
Chunk 1297
Chunk 1298
Chunk 1299
Chunk 1300
Chunk 1301
Chunk 1302
Chunk 1303
Chunk 1304
Chunk 1305
Chunk 1306
Chunk 1307
Chunk 1308
Chunk 1309
Chunk 1310
Chunk 1311
Chunk 1312
Chunk 1313
Chunk 1314
Chunk 1315
Chunk 1316
Chunk 1317
Chunk 1318
Chunk 1319
Chunk 1320
Chunk 1321
Chunk 1322
Chunk 1323
Chunk 1324
Chunk 1325
Chunk 1326
Chunk 1327
Chunk 1328
Chunk 1329
Chunk 1330
Chunk 1331
Chunk 1332
Chunk 1333
Chunk 1334
Chunk 1335
Chunk 1336
Chunk 1337
Chunk 1338
Chunk 1339
Chunk 1340
Chunk 1341
Chunk 1342
Chunk 1343
Chunk 1344
Chunk 1345
Chunk 1346
Chunk 1347
Chunk 1348
Chunk 1349
Chunk 1350
Chunk 1351
Chunk 1352
Chunk 1353
Chunk 1354
Chunk 1355
Chunk 1356
Chunk 1357
Chunk 1358
Chunk 1359
Chunk 1360
Chunk 1361
Chunk 1362
Chunk 1363
Chunk 1364
Chunk 1365
Chunk 1366
Chunk 1367
Chunk 1368
Chunk 1369
Chunk 1370
Chunk 1371
Chunk 1372
Chunk 1373
Chunk 1374
Chunk 1375
Chunk 1376
Chunk 1377
Chunk 1378
Chunk 1379
Chunk 1380
Chunk 1381
Chunk 1382
Chunk 1383
Chunk 1384
Chunk 1385
Chunk 1386
Chunk 1387
Chunk 1388
Chunk 1389
Chunk 1390
Chunk 1391
Chunk 1392
Chunk 1393
Chunk 1394
Chunk 1395
Chunk 1396
Chunk 1397
Chunk 1398
Chunk 1399
Chunk 1400
Chunk 1401
Chunk 1402
Chunk 1403
Chunk 1404
Chunk 1405
Chunk 1406
Chunk 1407
Chunk 1408
Chunk 1409
Chunk 1410
Chunk 1411
Chunk 1412
Chunk 1413
Chunk 1414
Chunk 1415
Chunk 1416
Chunk 1417
Chunk 1418
Chunk 1419
Chunk 1420
Chunk 1421
Chunk 1422
Chunk 1423
Chunk 1424
Chunk 1425
Chunk 1426
Chunk 1427
Chunk 1428
Chunk 1429
Chunk 1430
Chunk 1431
Chunk 1432
Chunk 1433
Chunk 1434
Chunk 1435
Chunk 1436
Chunk 1437
Chunk 1438
Chunk 1439
Chunk 1440
Chunk 1441
Chunk 1442
Chunk 1443
Chunk 1444
Chunk 1445
Chunk 1446
Chunk 1447
Chunk 1448
Chunk 1449
Chunk 1450
Chunk 1451
Chunk 1452
Chunk 1453
Chunk 1454
Chunk 1455
Chunk 1456
Chunk 1457
Chunk 1458
Chunk 1459
Chunk 1460
Chunk 1461
Chunk 1462
Chunk 1463
Chunk 1464
Chunk 1465
Chunk 1466
Chunk 1467
Chunk 1468
Chunk 1469
Chunk 1470
Chunk 1471
Chunk 1472
Chunk 1473
Chunk 1474
Chunk 1475
Chunk 1476
Chunk 1477
Chunk 1478
Chunk 1479
Chunk 1480
Chunk 1481
Chunk 1482
Chunk 1483
Chunk 1484
Chunk 1485
Chunk 1486
Chunk 1487
Chunk 1488
Chunk 1489
Chunk 1490
Chunk 1491
Chunk 1492
Chunk 1493
Chunk 1494
Chunk 1495
Chunk 1496
Chunk 1497
Chunk 1498
Chunk 1499
Chunk 1500
Chunk 1501
Chunk 1502
Chunk 1503
Chunk 1504
Chunk 1505
Chunk 1506
Chunk 1507
Chunk 1508
Chunk 1509
Chunk 1510
Chunk 1511
Chunk 1512
Chunk 1513
Chunk 1514
Chunk 1515
Chunk 1516
Chunk 1517
Chunk 1518
Chunk 1519
Chunk 1520
Chunk 1521
Chunk 1522
Chunk 1523
Chunk 1524
Chunk 1525
Chunk 1526
Chunk 1527
Chunk 1528
Chunk 1529
Chunk 1530
Chunk 1531
Chunk 1532
Chunk 1533
Chunk 1534
Chunk 1535
Chunk 1536
Chunk 1537
Chunk 1538
Chunk 1539
Chunk 1540
Chunk 1541
Chunk 1542
Chunk 1543
Chunk 1544
Chunk 1545
Chunk 1546
Chunk 1547
Chunk 1548
Chunk 1549
Chunk 1550
Chunk 1551
Chunk 1552
Chunk 1553
Chunk 1554
Chunk 1555
Chunk 1556
Chunk 1557
Chunk 1558
Chunk 1559
Chunk 1560
Chunk 1561
Chunk 1562
Chunk 1563
Chunk 1564
Chunk 1565
Chunk 1566
Chunk 1567
Chunk 1568
Chunk 1569
Chunk 1570
Chunk 1571
Chunk 1572
Chunk 1573
Chunk 1574
Chunk 1575
Chunk 1576
Chunk 1577
Chunk 1578
Chunk 1579
Chunk 1580
Chunk 1581
Chunk 1582
Chunk 1583
Chunk 1584
Chunk 1585
Chunk 1586
Chunk 1587
Chunk 1588
Chunk 1589
Chunk 1590
Chunk 1591
Chunk 1592
Chunk 1593
Chunk 1594
Chunk 1595
Chunk 1596
Chunk 1597
Chunk 1598
Chunk 1599
Chunk 1600
Chunk 1601
Chunk 1602
Chunk 1603
Chunk 1604
Chunk 1605
Chunk 1606
Chunk 1607
Chunk 1608
Chunk 1609
Chunk 1610
Chunk 1611
Chunk 1612
Chunk 1613
Chunk 1614
Chunk 1615
Chunk 1616
Chunk 1617
Chunk 1618
Chunk 1619
Chunk 1620
Chunk 1621
Chunk 1622
Chunk 1623
Chunk 1624
Chunk 1625
Chunk 1626
Chunk 1627
Chunk 1628
Chunk 1629
Chunk 1630
Chunk 1631
Chunk 1632
Chunk 1633
Chunk 1634
Chunk 1635
Chunk 1636
Chunk 1637
Chunk 1638
Chunk 1639
Chunk 1640
Chunk 1641
Chunk 1642
Chunk 1643
Chunk 1644
Chunk 1645
Chunk 1646
Chunk 1647
Chunk 1648
Chunk 1649
Chunk 1650
Chunk 1651
Chunk 1652
Chunk 1653
Chunk 1654
Chunk 1655
Chunk 1656
Chunk 1657
Chunk 1658
Chunk 1659
Chunk 1660
Chunk 1661
Chunk 1662
Chunk 1663
Chunk 1664
Chunk 1665
Chunk 1666
Chunk 1667
Chunk 1668
Chunk 1669
Chunk 1670
Chunk 1671
Chunk 1672
Chunk 1673
Chunk 1674
Chunk 1675
Chunk 1676
Chunk 1677
Chunk 1678
Chunk 1679
Chunk 1680
Chunk 1681
Chunk 1682
Chunk 1683
Chunk 1684
Chunk 1685
Chunk 1686
Chunk 1687
Chunk 1688
Chunk 1689
Chunk 1690
Chunk 1691
Chunk 1692
Chunk 1693
Chunk 1694
Chunk 1695
Chunk 1696
Chunk 1697
Chunk 1698
Chunk 1699
Chunk 1700
Chunk 1701
Chunk 1702
Chunk 1703
Chunk 1704
Chunk 1705
Chunk 1706
Chunk 1707
Chunk 1708
Chunk 1709
Chunk 1710
Chunk 1711
Chunk 1712
Chunk 1713
Chunk 1714
Chunk 1715
Chunk 1716
Chunk 1717
Chunk 1718
Chunk 1719
Chunk 1720
Chunk 1721
Chunk 1722
Chunk 1723
Chunk 1724
Chunk 1725
Chunk 1726
Chunk 1727
Chunk 1728
Chunk 1729
Chunk 1730
Chunk 1731
Chunk 1732
Chunk 1733
Chunk 1734
Chunk 1735
Chunk 1736
Chunk 1737
Chunk 1738
Chunk 1739
Chunk 1740
Chunk 1741
Chunk 1742
Chunk 1743
Chunk 1744
Chunk 1745
Chunk 1746
Chunk 1747
Chunk 1748
Chunk 1749
Chunk 1750
Chunk 1751
Chunk 1752
Chunk 1753
Chunk 1754
Chunk 1755
Chunk 1756
Chunk 1757
Chunk 1758
Chunk 1759
Chunk 1760
Chunk 1761
Chunk 1762
Chunk 1763
Chunk 1764
Chunk 1765
Chunk 1766
Chunk 1767
Chunk 1768
Chunk 1769
Chunk 1770
Chunk 1771
Chunk 1772
Chunk 1773
Chunk 1774
Chunk 1775
Chunk 1776
Chunk 1777
Chunk 1778
Chunk 1779
Chunk 1780
Chunk 1781
Chunk 1782
Chunk 1783
Chunk 1784
Chunk 1785
Chunk 1786
Chunk 1787
Chunk 1788
Chunk 1789
Chunk 1790
Chunk 1791
Chunk 1792
Chunk 1793
Chunk 1794
Chunk 1795
Chunk 1796
Chunk 1797
Chunk 1798
Chunk 1799
Chunk 1800
Chunk 1801
Chunk 1802
Chunk 1803
Chunk 1804
Chunk 1805
Chunk 1806
Chunk 1807
Chunk 1808
Chunk 1809
Chunk 1810
Chunk 1811
Chunk 1812
Chunk 1813
Chunk 1814
Chunk 1815
Chunk 1816
Chunk 1817
Chunk 1818
Chunk 1819
Chunk 1820
Chunk 1821
Chunk 1822
Chunk 1823
Chunk 1824
Chunk 1825
Chunk 1826
Chunk 1827
Chunk 1828
Chunk 1829
Chunk 1830
Chunk 1831
Chunk 1832
Chunk 1833
Chunk 1834
Chunk 1835
Chunk 1836
Chunk 1837
Chunk 1838
Chunk 1839
Chunk 1840
Chunk 1841
Chunk 1842
Chunk 1843
Chunk 1844
Chunk 1845
Chunk 1846
Chunk 1847
Chunk 1848
Chunk 1849
Chunk 1850
Chunk 1851
Chunk 1852
Chunk 1853
Chunk 1854
Chunk 1855
Chunk 1856
Chunk 1857
Chunk 1858
Chunk 1859
Chunk 1860
Chunk 1861
Chunk 1862
Chunk 1863
Chunk 1864
Chunk 1865
Chunk 1866
Chunk 1867
Chunk 1868
Chunk 1869
Chunk 1870
Chunk 1871
Chunk 1872
Chunk 1873
Chunk 1874
Chunk 1875
Chunk 1876
Chunk 1877
Chunk 1878
Chunk 1879
Chunk 1880
Chunk 1881
Chunk 1882
Chunk 1883
Chunk 1884
Chunk 1885
Chunk 1886
Chunk 1887
Chunk 1888
Chunk 1889
Chunk 1890
Chunk 1891
Chunk 1892
Chunk 1893
Chunk 1894
Chunk 1895
Chunk 1896
Chunk 1897
Chunk 1898
Chunk 1899
Chunk 1900
Chunk 1901
Chunk 1902
Chunk 1903
Chunk 1904
Chunk 1905
Chunk 1906
Chunk 1907
Chunk 1908
Chunk 1909
Chunk 1910
Chunk 1911
Chunk 1912
Chunk 1913
Chunk 1914
Chunk 1915
Chunk 1916
Chunk 1917
Chunk 1918

In [ ]:
df1 = pd.read_csv('../../Data/은평구_스테이션_군집화_1차_자전거댓수_추가.csv')
df1['시작_대여소_ID'] = df1['대여소_ID']
addr = df1['대여소_ID'].unique().tolist()

In [60]:
save = station_raw1[(station_raw1['시작_대여소_ID'].isin(addr)) | (station_raw1['종료_대여소_ID'].isin(addr))]
save

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리
27,20250109,출발시간,900.0,ST-2775,응암1동_032_1,ST-462,응암3동_002_2,1,9,1379
28,20250109,출발시간,1905.0,ST-462,응암3동_002_2,ST-2775,응암1동_032_1,1,10,1368
32,20250109,출발시간,1625.0,ST-2782,갈현1동_002_2,ST-481,구산동_029_1,1,8,1281
44,20250109,출발시간,1450.0,ST-3169,구산동_060_1,ST-1036,역촌동_044_1,1,5,1455
89,20250109,출발시간,1610.0,ST-2261,진관동_106_1,ST-3126,진관동_076_1,1,8,1060
...,...,...,...,...,...,...,...,...,...,...
106329,20251231,도착시간,1740.0,ST-465,응암1동_059_1,ST-2250,녹번동_021_1,1,4,870
106351,20251231,도착시간,245.0,ST-2153,신수동_027_1,ST-3095,증산동_004_1,1,39,5744
106377,20251231,도착시간,1425.0,ST-479,역촌동_080_1,ST-459,녹번동_043_1,1,18,1306
106467,20251231,도착시간,950.0,ST-3279,수색동_004_2,ST-3239,여의동_006_8,1,52,10431
106560,20251231,도착시간,1950.0,ST-455,응암1동_023_1,ST-460,응암3동_007_1,1,6,1162

In [61]:
save.reset_index(drop=True, inplace=True)
save.to_csv('../../Data/2025.csv',index=None)